version: '3.8'
services:
  waha:
    image: devlikeapro/waha:latest
    container_name: wpp_bot_waha
    restart: always
    ports:
      - '3000:3000'
    networks:
      - waha_net

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wpp_bot_api
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - ./chroma_data:/app/chroma_data
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - WAHA_API_URL=http://wpp_bot_waha:3000
    networks:
      - waha_net

networks:
  waha_net:
    driver: bridge
